apiVersion: v1
kind: ConfigMap
metadata:
  name: rpmdm-ui-properties
  namespace: {{ .Values.namespace }}
data:
  mdm_web_service.properties: |
    mdm.host=0.0.0.0
    mdm.port=9090
    authentication.host=rp-mdm-auth
    authentication.port=443
    user.host=rp-mdm-user
    user.port=443
    permission.host=rp-mdm-perm
    permission.port=443
    core.port=443
    core.host=rp-mdm-core
    trace_messages=true
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log4js-config
  namespace: {{ .Values.namespace }}
data:
  log4js_config.json: |
    {
    "appenders": {"console": { "type": "console" }},
     "categories": {
     "MDM Server": { "appenders": ["console"], "level": "debug" },
     "default": { "appenders": ["console"], "level": "debug" }
      }
    }


