apiVersion: v1
kind: ConfigMap
metadata:
  name: rpmdm-perm-properties
  namespace: {{ .Values.global.namespace }}
data:
  mdm_permission_service.properties: |
    permission.port=9908
    user.url=http://rp-mdm-user:80
    log.url=http://rp-mdm-log:80
    authentication.url=http://rp-mdm-auth:80
    trace_messages=false
