apiVersion: v1
kind: ConfigMap
metadata:
  name: rpmdm-user-properties
  namespace: {{ .Values.namespace }}
data:
  mdm_user_service.properties: |
    user.port=9903
    authentication.url=http://rp-mdm-auth:80
    log.url=http://rp-mdm-log:80
    trace_messages=false

