apiVersion: v1
kind: ConfigMap
metadata:
  name: rpmdm-ui-properties
  namespace: {{ .Values.global.namespace }}
data:
  mdm_web_service.properties: |
    mdm.port=9090
    authentication.url=http://rp-mdm-auth:80
    user.url=http://rp-mdm-user:80
    log.url=http://rp-mdm-log:80
    core.url=http://rp-mdm-core:80
    permission.url=http://rp-mdm-perm:80
    trace_messages=true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log4js-config
  namespace: {{ .Values.global.namespace }}
data:
  log4js_config.json: |
    {
    "appenders": {"console": { "type": "console" }},
     "categories": {
     "MDM Server": { "appenders": ["console"], "level": "debug" },
     "default": { "appenders": ["console"], "level": "debug" }
      }
    }
