apiVersion: v1
kind: ConfigMap
metadata:
  name: rpmdm-auth-properties
  namespace: {{ .Values.namespace }}
data:
  mdm_authentication_service.properties: |
    authentication.active_dir.url={{ .Values.ldap.active_dir_url }}
    authentication.active_dir.domain={{ .Values.ldap.active_dir_domain }}
    authentication.port=9901
    user.url=http://rp-mdm-user:80
    log.url=http://rp-mdm-log:80
    trace_messages=false
