---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.user }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.names.user }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.names.user }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.user }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      serviceAccountName: {{ .Values.serviceAccount.names.user }}
      containers:
        - name: {{ .Values.names.user }}
          image: "{{ .Values.images.repository.user }}:{{ .Values.images.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port.user }}
          env:
          - name: MDM_MONGO_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb_connection_secret }}
                key: MONGO_CONNECTION_STRING
          - name: JAVA_API_SERVICE
            value: {{ .Values.java_api_service }}
          volumeMounts:
            - name: rpmdm-user-properties
              mountPath: /usr/local/share/redpointmdm/
            - name: log4js-config
              mountPath: /usr/local/app/user-service/log4js_config.json
              subPath: log4js_config.json
      volumes:
        - name: rpmdm-user-properties
          configMap:
            name: rpmdm-user-properties
        - name: log4js-config
          configMap:
            name: log4js-config
      {{- if eq .Values.global.nodeConstraint "enabled" }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}