---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.perm }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.names.perm }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.names.perm }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.perm }}
      annotations:
        container.apparmor.security.beta.kubernetes.io/rp-mdm-perm: runtime/default
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      serviceAccountName: {{ .Values.serviceAccount.names.perm }}
      containers:
        - name: {{ .Values.names.perm }}
          image: "{{ .Values.images.repository.perm }}:{{ .Values.images.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.service.port.perm }}
          resources:
            {{- toYaml .Values.resources_ui | nindent 12 }}
          env:
          - name: MDM_MONGO_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb_connection_secret }}
                key: MONGO_CONNECTION_STRING
          - name: JAVA_API_SERVICE
            value: {{ .Values.java_api_service }}
          volumeMounts:
            - name: rpmdm-perm-properties
              mountPath: /usr/local/share/redpointmdm/
            - name: log4js-config
              mountPath: /usr/local/app/permission-service/log4js_config.json
              subPath: log4js_config.json
      nodeSelector:
        {{ .Values.nodeSelector.key }}: {{ .Values.nodeSelector.value }}
      tolerations:
        - effect: NoSchedule
          key: {{ .Values.nodeSelector.key }}
          operator: Equal 
          value: {{ .Values.nodeSelector.value }}
      volumes:
        - name: rpmdm-perm-properties
          configMap:
            name: rpmdm-perm-properties
        - name: log4js-config
          configMap:
            name: log4js-config