apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.log }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.names.log }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.names.log }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.log }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      serviceAccountName: {{ .Values.serviceAccount.names.log }}
      containers:
        - name: {{ .Values.names.log }}         
          image:  "{{ .Values.images.repository.log }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port.log }}
          env:
          - name: MDM_MONGO_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb_connection_secret }}
                key: MONGO_CONNECTION_STRING
          volumeMounts:
            - name: rpmdm-log-properties
              mountPath: /usr/local/share/redpointmdm/
      volumes:
        - name: rpmdm-log-properties
          configMap:
            name: rpmdm-log-properties
      {{- if eq .Values.global.nodeConstraint "enabled" }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}

