apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.core }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.names.core }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.names.core }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.core }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      serviceAccountName: {{ .Values.serviceAccount.names.core }}
      containers:
        - name: {{ .Values.names.core }}         
          image:  "{{ .Values.images.repository.core }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port.core }}
          env:
          - name: MDM_MONGO_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb_connection_secret }}
                key: MONGO_CONNECTION_STRING
          volumeMounts:
            - name: rpmdm-core-properties
              mountPath: /usr/local/share/redpointmdm/
      volumes:
        - name: rpmdm-core-properties
          configMap:
            name: rpmdm-core-properties
