apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.names.ui }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.names.ui }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.names.ui }}
  template:
    metadata:
      labels:
        app: {{ .Values.names.ui }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      serviceAccountName: {{ .Values.serviceAccount.names.ui }}
      containers:
        - name: {{ .Values.names.ui }}         
          image:  "{{ .Values.images.repository.ui }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port.ui }}
          env:
          - name: MDM_MONGO_URI
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mongodb_connection_secret }}
                key: MONGO_CONNECTION_STRING
          volumeMounts:
            - name: rpmdm-ui-properties
              mountPath: /usr/local/share/redpointmdm/
            - name: log4js-config
              mountPath: /usr/local/app/mdm-ui/log4js_config.json
              subPath: log4js_config.json
      volumes:
        - name: rpmdm-ui-properties
          configMap:
            name: rpmdm-ui-properties
        - name: log4js-config
          configMap:
            name: log4js-config

