apiVersion: v1
kind: Secret
metadata:
  name: mongodb-conn-string
  namespace: {{ .Values.global.namespace }}
data:
  MONGO_CONNECTION_STRING: {{ .Values.mongodb.connection_string | b64enc }}
type: Opaque
