apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.ui }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.names.ui }} 
spec:
  ports:
    - port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.service.port.ui }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.names.ui }}
  selector:
    app: {{ .Values.names.ui}}

  