apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.auth }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.names.auth }} 
spec:
  ports:
    - port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.service.port.auth }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.names.auth }}
  selector:
    app: {{ .Values.names.auth}}

