apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.log }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.service.names.log }} 
spec:
  ports:
    - port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.service.port.log }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.names.log }}
  selector:
    app: {{ .Values.names.log}}