apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.auth }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.service.names.auth }} 
spec:
  ports:
    - port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.service.port.auth }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.names.auth }}
  selector:
    app: {{ .Values.names.auth}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.auth }}-tcp
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.names.auth }} 
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: {{ .Values.ingress.internal | quote }}
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: {{ .Values.ingress.subnet_name | quote }}
spec:
  ports:
    - port: 9901
      targetPort: 9901
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Values.names.auth}}
  type: LoadBalancer