apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.ui }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.service.names.ui }} 
spec:
  ports:
    - port: 80
      targetPort: 9090
      name: {{ .Values.service.names.ui }}
  selector:
    app: {{ .Values.names.ui}}
    
