apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.core }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.service.names.core }} 
spec:
  ports:
    - port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.service.port.core }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.names.core }}
  selector:
    app: {{ .Values.names.core}}

---
{{- if eq .Values.nginx.cloudProvider "amazon" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.core }}-tcp
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.names.core }} 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"    
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'    
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  ports:
    - port: 9902
      targetPort: 9902
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Values.names.core}}
  type: LoadBalancer
{{- end }}

---
{{- if eq .Values.nginx.cloudProvider "azure" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.core }}-tcp
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.names.core }} 
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: {{ .Values.ingress.internal | quote }}
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: {{ .Values.ingress.subnet_name | quote }}
spec:
  ports:
    - port: 9902
      targetPort: 9902
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Values.names.core}}
  type: LoadBalancer
{{- end }}