apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.ui }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.names.ui }} 
spec:
  ports:
    - port: {{ .Values.service.port.https }}
      targetPort: {{ .Values.service.port.ui }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.names.ui }}
  selector:
    app: {{ .Values.names.ui}}
    
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.names.ui }}-tcp
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.names.ui }} 
#  annotations:
#    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
#   service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snet-rgoc-nonprod-eus2-aks"
spec:
  ports:
    - port: 9902
      targetPort: 9902
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Values.names.ui}}
  type: LoadBalancer
  
