apiVersion: v2
name: redpoint-mdm

description: A Helm chart for Redpoint Master Data Management (MDM)

type: application
version: 1.6.4
appVersion: "1.6.4"

maintainers:
  - name: Redpoint Global
    email: support@redpointglobal.com
