apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ include "custom.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: 9vDR1p8Q1KEO
      volumes:
        - name: mongodb-data
          hostPath:
            path: /mongo
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ include "custom.namespace" . }}
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
